baseURL = 'https://shioriblog.github.io/'
languageCode = 'en-us'
title = 'Shiori'
theme = "minos"

[params]
  author = "Shiori"
  paginate = 10
  noPostNavigation = true
  subtitle = 'Welcome to SHIORI’s tiny little world☕.'


[taxonomies]
   tag = "tags"

[outputs]
  home = ['html']

[mediaTypes]
  [mediaTypes."application/rss+xml"]
    suffixes = ["rss"]
    delimiter = "."

  
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Friends"
  url = "/friends/"
  weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
title = "Tags"
url = "/tags/"
weight = 3


