baseURL = 'https://shioriblog.github.io/'
languageCode = 'en-us'
title = 'Shiori'
theme = "minos"

[params]
  author = "Shiori"
  paginate = 10
  noPostNavigation = true
  subtitle = 'Welcome to SHIORI’s tiny little world☕.'

rssLimit = 10  # 限制 RSS 文章输出的数量
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "Shiori"

[taxonomies]
   tag = "tags"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Friends"
  url = "/friends/"
  weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
title = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
  name = "RSS"
  url = "/index.xml/"
  weight = 4
