baseURL = 'https://shioriblog.github.io/'
languageCode = 'en-us'
title = 'Shiori'
theme = "paper"
disqusShortname = 'Hello World!'

[params]

  color = 'linen'                           

  avatar = 'GRAVATAR_EMAIL'                 
  name = 'Shiori'
  bio = 'Hi'

  